version: "3"

services:
  web1:
    image: httpd:2.2.34-alpine
    container_name: web1
    ports: 
      - "80"
      - "443"
    volumes:
      - ${PWD}/web1:/usr/local/apache2/htdocs

  jwknz:
    image: node:10.6.0-alpine
    container_name: jwknz_cv
    ports: 
      - "80"
      - "443"
      - "3000"
    working_dir: /app
    command: "node app"
    volumes:
      - ${PWD}:/app
      
volumes:
  data-store:

